name: ⛅ Keys
on:
  schedule:
    # at 12:53 on 2nd of every month: crontab.guru/#53_12_2_*_*
    - cron: '53 12 2 * *'
  workflow_dispatch:
    # allow manual runs

jobs:
  deploy:
    name: 🏇 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 🏗 Wrangler
        run: npm i -g wrangler

      # ref: github.com/cloudflare/wrangler-action/blob/master/entrypoint.sh
      - name: 📚 Exec
        run: node ./src/node/prodkeys.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: ⛳️ Notice
        # docs.github.com/en/actions/learn-github-actions/expressions
        if: ${{ success() }}
        run: |
          echo "::notice::new keys set"
